// <auto-generated />
using MaestroTech.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaestroTech.Infrastructure.Migrations
{
    [DbContext(typeof(MaestroTechDbContext))]
    [Migration("20240706180224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaestroTech.Domain.Entities.Culto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDaSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Cultos");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Musica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cantores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDePreferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("LinkSpotify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkYouTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Musicas");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Culto", b =>
                {
                    b.HasOne("MaestroTech.Domain.Entities.Igreja", "Igreja")
                        .WithMany("DiasDeCulto")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Musica", b =>
                {
                    b.HasOne("MaestroTech.Domain.Entities.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("MaestroTech.Domain.Entities.Igreja", "Igreja")
                        .WithMany("Usuarios")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("MaestroTech.Domain.Entities.Igreja", b =>
                {
                    b.Navigation("DiasDeCulto");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
